@echo off
SET RT11EXE=C:\bin\rt11\rt11.exe
DEL /S /Q *-11.log *-11.SAV *-11.MAP *-11.STB > NUL
rem
echo ASHC4
CD ASHC4
%RT11EXE% LINK ASHC4/SYMBOLTABLE/MAP > ASHC4-11.log
RENAME ASHC4.SAV ASHC4-11.SAV
RENAME ASHC4.MAP ASHC4-11.MAP
RENAME ASHC4.STB ASHC4-11.STB
rem
echo DISSAV-DBIT
CD ..\DISSAV-DBIT
%RT11EXE% LINK DISSAV/SYMBOLTABLE/MAP > DISSAV-11.log
RENAME DISSAV.SAV DISSAV-11.SAV
RENAME DISSAV.MAP DISSAV-11.MAP
RENAME DISSAV.STB DISSAV-11.STB
rem
echo EXPRES-24
CD ..\EXPRES-24
%RT11EXE% LINK EXPRES/SYMBOLTABLE/MAP > EXPRES-11.log
RENAME EXPRES.SAV EXPRES-11.SAV
RENAME EXPRES.MAP EXPRES-11.MAP
RENAME EXPRES.STB EXPRES-11.STB
rem
echo EXPRES-BK-12
CD ..\EXPRES-BK-12
%RT11EXE% LINK EXPRES/SYMBOLTABLE/MAP > EXPRES-11.log
RENAME EXPRES.SAV EXPRES-11.SAV
RENAME EXPRES.MAP EXPRES-11.MAP
RENAME EXPRES.STB EXPRES-11.STB
rem
echo EMUL-DISK25
CD ..\EMUL-DISK25
%RT11EXE% LINK EMUL/SYMBOLTABLE/MAP > EMUL-11.log
RENAME EMUL.SAV EMUL-11.SAV
RENAME EMUL.MAP EMUL-11.MAP
RENAME EMUL.STB EMUL-11.STB
rem
echo FCU
CD ..\FCU
%RT11EXE% LINK FCU/SYMBOLTABLE/MAP,FCUE,FCUMNG,FCUD,SELF > FCU-11.log
RENAME FCU.SAV FCU-11.SAV
RENAME FCU.MAP FCU-11.MAP
RENAME FCU.STB FCU-11.STB
rem
echo FIG-FORTH-1-3
CD ..\FIG-FORTH-1-3
%RT11EXE% LINK FORTH/SYMBOLTABLE/MAP > FORTH-11.log
RENAME FORTH.SAV FORTH-11.SAV
RENAME FORTH.MAP FORTH-11.MAP
RENAME FORTH.STB FORTH-11.STB
rem
echo GAD2-HOBOT
CD ..\GAD2-HOBOT
%RT11EXE% LINK GAD2/SYMBOLTABLE/MAP > GAD2-11.log
RENAME GAD2.SAV GAD2-11.SAV
RENAME GAD2.MAP GAD2-11.MAP
RENAME GAD2.STB GAD2-11.STB
rem
echo HAND-11
CD ..\HAND-11
%RT11EXE% LINK HAND/SYMBOLTABLE/MAP > HAND-11.log
RENAME HAND.SAV HAND-11.SAV
RENAME HAND.MAP HAND-11.MAP
RENAME HAND.STB HAND-11.STB
rem
echo HANDLE-503
CD ..\HANDLE-503
%RT11EXE% LINK HANDLE/SYMBOLTABLE/MAP > HANDLE-11.log
RENAME HANDLE.SAV HANDLE-11.SAV
RENAME HANDLE.MAP HANDLE-11.MAP
RENAME HANDLE.STB HANDLE-11.STB
rem
echo HELLO
CD ..\HELLO
%RT11EXE% LINK HELLO/SYMBOLTABLE/MAP > HELLO-11.log
RENAME HELLO.SAV HELLO-11.SAV
RENAME HELLO.MAP HELLO-11.MAP
RENAME HELLO.STB HELLO-11.STB
rem
echo HWYENC-62
CD ..\HWYENC-62
%RT11EXE% LINK HWYENC/SYMBOLTABLE/MAP > HWYENC-11.log
RENAME HWYENC.SAV HWYENC-11.SAV
RENAME HWYENC.MAP HWYENC-11.MAP
RENAME HWYENC.STB HWYENC-11.STB
rem
echo INTERFACE-DISK02
CD ..\INTERFACE-DISK02
%RT11EXE% LINK IF/SYMBOLTABLE/MAP,IFMAIN,IFCOPY,IFTRP,IFSPEC,IFPP > IF-11.log
RENAME IF.SAV IF-11.SAV
RENAME IF.MAP IF-11.MAP
RENAME IF.STB IF-11.STB
rem
echo LZSAV
CD ..\LZSAV
%RT11EXE% LINK LZSAV/SYMBOLTABLE/MAP > LZSAV-11.log
RENAME LZSAV.SAV LZSAV-11.SAV
RENAME LZSAV.MAP LZSAV-11.MAP
RENAME LZSAV.STB LZSAV-11.STB
rem
echo MAIN-50
CD ..\MAIN-50
%RT11EXE% LINK MAIN/SYMBOLTABLE/MAP,LEVELS > MAIN-11.log
RENAME MAIN.SAV MAIN-11.SAV
RENAME MAIN.MAP MAIN-11.MAP
RENAME MAIN.STB MAIN-11.STB
rem
echo MUL
CD ..\MUL
%RT11EXE% LINK MUL/SYMBOLTABLE/MAP > MUL-11.log
RENAME MUL.SAV MUL-11.SAV
RENAME MUL.MAP MUL-11.MAP
RENAME MUL.STB MUL-11.STB
rem
echo PAKDMP-PHOOKY
CD ..\PAKDMP-PHOOKY
%RT11EXE% LINK PAKDMP/SYMBOLTABLE/MAP > PAKDMP-11.log
RENAME PAKDMP.SAV PAKDMP-11.SAV
RENAME PAKDMP.MAP PAKDMP-11.MAP
RENAME PAKDMP.STB PAKDMP-11.STB
rem
echo PAKWRT-PHOOKY
CD ..\PAKWRT-PHOOKY
%RT11EXE% LINK PAKWRT/SYMBOLTABLE/MAP > PAKWRT-11.log
RENAME PAKWRT.SAV PAKWRT-11.SAV
RENAME PAKWRT.MAP PAKWRT-11.MAP
RENAME PAKWRT.STB PAKWRT-11.STB
rem
echo PCM-DISK09
CD ..\PCM-DISK09
%RT11EXE% LINK PCM/SYMBOLTABLE/MAP > PCM-11.log
RENAME PCM.SAV PCM-11.SAV
RENAME PCM.MAP PCM-11.MAP
RENAME PCM.STB PCM-11.STB
rem
echo PDPCLK
CD ..\PDPCLK
%RT11EXE% LINK PDPCLK/SYMBOLTABLE/MAP > PDPCLK-11.log
RENAME PDPCLK.SAV PDPCLK-11.SAV
RENAME PDPCLK.MAP PDPCLK-11.MAP
RENAME PDPCLK.STB PDPCLK-11.STB
rem
echo PRIM-FORTRANIV
CD ..\PRIM-FORTRANIV
%RT11EXE% LINK PRIM/SYMBOLTABLE/MAP,FORLIB > PRIM-11.log
RENAME PRIM.SAV PRIM-11.SAV
RENAME PRIM.MAP PRIM-11.MAP
RENAME PRIM.STB PRIM-11.STB
rem
echo RTLEM
CD ..\RTLEM
%RT11EXE% LINK RTLEM/SYMBOLTABLE/MAP > RTLEM-11.log
RENAME RTLEM.SAV RTLEM-11.SAV
RENAME RTLEM.MAP RTLEM-11.MAP
RENAME RTLEM.STB RTLEM-11.STB
rem
echo SATMON-HADI3DSK
CD ..\SATMON-HADI3DSK
%RT11EXE% LINK SATMON/SYMBOLTABLE/MAP > SATMON-11.log
RENAME SATMON.SAV SATMON-11.SAV
RENAME SATMON.MAP SATMON-11.MAP
RENAME SATMON.STB SATMON-11.STB
rem
echo SNDOFF-ANDREY14
CD ..\SNDOFF-ANDREY14
%RT11EXE% LINK SNDOFF/SYMBOLTABLE/MAP > SNDOFF-11.log
RENAME SNDOFF.SAV SNDOFF-11.SAV
RENAME SNDOFF.MAP SNDOFF-11.MAP
RENAME SNDOFF.STB SNDOFF-11.STB
rem
echo SOKOBA
CD ..\SOKOBA
%RT11EXE% LINK SOKOBA/SYMBOLTABLE/MAP,SOKDAT,ALP,RALP,SOKMAZ > SOKOBA-11.log
RENAME SOKOBA.SAV SOKOBA-11.SAV
RENAME SOKOBA.MAP SOKOBA-11.MAP
RENAME SOKOBA.STB SOKOBA-11.STB
rem
echo SOKOED
CD ..\SOKOED
%RT11EXE% LINK SOKOED/SYMBOLTABLE/MAP,SOKED,SOKDAT > SOKOED-11.log
RENAME SOKOED.SAV SOKOED-11.SAV
RENAME SOKOED.MAP SOKOED-11.MAP
RENAME SOKOED.STB SOKOED-11.STB
rem
echo SPCINV
CD ..\SPCINV
%RT11EXE% LINK SPCINV/SYMBOLTABLE/MAP > SPCINV-11.log
RENAME SPCINV.SAV SPCINV-11.SAV
RENAME SPCINV.MAP SPCINV-11.MAP
RENAME SPCINV.STB SPCINV-11.STB
rem
echo TEST-PASCAL
CD ..\TEST-PASCAL
%RT11EXE% LINK TEST/SYMBOLTABLE/MAP,PASCAL > TEST-11.log
RENAME TEST.SAV TEST-11.SAV
RENAME TEST.MAP TEST-11.MAP
RENAME TEST.STB TEST-11.STB
rem
echo TSPAL-01B
CD ..\TSPAL-01B
%RT11EXE% LINK TSPAL/SYMBOLTABLE/MAP > TSPAL-11.log
RENAME TSPAL.SAV TSPAL-11.SAV
RENAME TSPAL.MAP TSPAL-11.MAP
RENAME TSPAL.STB TSPAL-11.STB
rem
echo TSTVM1-01A
CD ..\TSTVM1-01A
%RT11EXE% LINK TSTVM1/SYMBOLTABLE/MAP > TSTVM1-11.log
RENAME TSTVM1.SAV TSTVM1-11.SAV
RENAME TSTVM1.MAP TSTVM1-11.MAP
RENAME TSTVM1.STB TSTVM1-11.STB
rem
echo TSTVM2-03A
CD ..\TSTVM2-03A
%RT11EXE% LINK TSTVM2/SYMBOLTABLE/MAP > TSTVM2-11.log
RENAME TSTVM2.SAV TSTVM2-11.SAV
RENAME TSTVM2.MAP TSTVM2-11.MAP
RENAME TSTVM2.STB TSTVM2-11.STB
rem
echo UKFONT
CD ..\UKFONT
%RT11EXE% LINK UKFONT/SYMBOLTABLE/MAP > UKFONT-11.log
RENAME UKFONT.SAV UKFONT-11.SAV
RENAME UKFONT.MAP UKFONT-11.MAP
RENAME UKFONT.STB UKFONT-11.STB
CD ..
