@echo off
SET RT11EXE=C:\bin\rt11\rt11.exe
DEL /S /Q *-11.log *-11.SAV *-11.MAP *-11.STB > NUL
rem
echo ASHC4
CD ASHC4
%RT11EXE% LINK ASHC4/SYMBOLTABLE/MAP > ASHC4-11.log
RENAME ASHC4.SAV ASHC4-11.SAV
RENAME ASHC4.MAP ASHC4-11.MAP
RENAME ASHC4.STB ASHC4-11.STB
rem
echo EXPRES-24
CD ..\EXPRES-24
%RT11EXE% LINK EXPRES/SYMBOLTABLE/MAP > EXPRES-11.log
RENAME EXPRES.SAV EXPRES-11.SAV
RENAME EXPRES.MAP EXPRES-11.MAP
RENAME EXPRES.STB EXPRES-11.STB
rem
echo EXPRES-BK-12
CD ..\EXPRES-BK-12
%RT11EXE% LINK EXPRES/SYMBOLTABLE/MAP > EXPRES-11.log
RENAME EXPRES.SAV EXPRES-11.SAV
RENAME EXPRES.MAP EXPRES-11.MAP
RENAME EXPRES.STB EXPRES-11.STB
rem
echo FCU
CD ..\FCU
%RT11EXE% LINK FCU/SYMBOLTABLE/MAP,FCUE,FCUMNG,FCUD,SELF > FCU-11.log
RENAME FCU.SAV FCU-11.SAV
RENAME FCU.MAP FCU-11.MAP
RENAME FCU.STB FCU-11.STB
rem
echo HELLO
CD ..\HELLO
%RT11EXE% LINK HELLO/SYMBOLTABLE/MAP > HELLO-11.log
RENAME HELLO.SAV HELLO-11.SAV
RENAME HELLO.MAP HELLO-11.MAP
RENAME HELLO.STB HELLO-11.STB
rem
echo HWYENC-62
CD ..\HWYENC-62
%RT11EXE% LINK HWYENC/SYMBOLTABLE/MAP > HWYENC-11.log
RENAME HWYENC.SAV HWYENC-11.SAV
RENAME HWYENC.MAP HWYENC-11.MAP
RENAME HWYENC.STB HWYENC-11.STB
rem
echo LZSAV
CD ..\LZSAV
%RT11EXE% LINK LZSAV/SYMBOLTABLE/MAP > LZSAV-11.log
RENAME LZSAV.SAV LZSAV-11.SAV
RENAME LZSAV.MAP LZSAV-11.MAP
RENAME LZSAV.STB LZSAV-11.STB
rem
echo MAIN-50
CD ..\MAIN-50
%RT11EXE% LINK MAIN/SYMBOLTABLE/MAP,LEVELS > MAIN-11.log
RENAME MAIN.SAV MAIN-11.SAV
RENAME MAIN.MAP MAIN-11.MAP
RENAME MAIN.STB MAIN-11.STB
rem
echo MUL
CD ..\MUL
%RT11EXE% LINK MUL/SYMBOLTABLE/MAP > MUL-11.log
RENAME MUL.SAV MUL-11.SAV
RENAME MUL.MAP MUL-11.MAP
RENAME MUL.STB MUL-11.STB
rem
echo RTLEM
CD ..\RTLEM
%RT11EXE% LINK RTLEM/SYMBOLTABLE/MAP > RTLEM-11.log
RENAME RTLEM.SAV RTLEM-11.SAV
RENAME RTLEM.MAP RTLEM-11.MAP
RENAME RTLEM.STB RTLEM-11.STB
rem
echo SOKOBA
CD ..\SOKOBA
%RT11EXE% LINK SOKOBA/SYMBOLTABLE/MAP,SOKDAT,ALP,RALP,SOKMAZ > SOKOBA-11.log
RENAME SOKOBA.SAV SOKOBA-11.SAV
RENAME SOKOBA.MAP SOKOBA-11.MAP
RENAME SOKOBA.STB SOKOBA-11.STB
rem
echo SOKOED
CD ..\SOKOED
%RT11EXE% LINK SOKOED/SYMBOLTABLE/MAP,SOKED,SOKDAT > SOKOED-11.log
RENAME SOKOED.SAV SOKOED-11.SAV
RENAME SOKOED.MAP SOKOED-11.MAP
RENAME SOKOED.STB SOKOED-11.STB
rem
echo TSPAL-01B
CD ..\TSPAL-01B
%RT11EXE% LINK TSPAL/SYMBOLTABLE/MAP > TSPAL-11.log
RENAME TSPAL.SAV TSPAL-11.SAV
RENAME TSPAL.MAP TSPAL-11.MAP
RENAME TSPAL.STB TSPAL-11.STB
rem
echo TSTVM2-03A
CD ..\TSTVM2-03A
%RT11EXE% LINK TSTVM2/SYMBOLTABLE/MAP > TSTVM2-11.log
RENAME TSTVM2.SAV TSTVM2-11.SAV
RENAME TSTVM2.MAP TSTVM2-11.MAP
RENAME TSTVM2.STB TSTVM2-11.STB
CD ..
