@echo off
SET PCLINK11=..\..\Debug\pclink11.exe
DEL /S /Q *-my.log *-my.SAV *-my.MAP *-my.STB > NUL
rem
echo EXPRES-24
CD EXPRES-24
%PCLINK11% EXPRES.OBJ > EXPRES-my.log
RENAME EXPRES.SAV EXPRES-my.SAV
RENAME EXPRES.MAP EXPRES-my.MAP
RENAME EXPRES.STB EXPRES-my.STB
rem
echo EXPRES-BK-12
CD ..\EXPRES-BK-12
%PCLINK11% EXPRES.OBJ > EXPRES-my.log
RENAME EXPRES.SAV EXPRES-my.SAV
RENAME EXPRES.MAP EXPRES-my.MAP
RENAME EXPRES.STB EXPRES-my.STB
rem
echo FCU
CD ..\FCU
%PCLINK11% FCU.OBJ FCUE.OBJ FCUMNG.OBJ FCUD.OBJ SELF.OBJ > FCU-my.log
RENAME FCU.SAV FCU-my.SAV
RENAME FCU.MAP FCU-my.MAP
RENAME FCU.STB FCU-my.STB
rem
echo HELLO
CD ..\HELLO
%PCLINK11% HELLO.OBJ > HELLO-my.log
RENAME HELLO.SAV HELLO-my.SAV
RENAME HELLO.MAP HELLO-my.MAP
RENAME HELLO.STB HELLO-my.STB
rem
echo HWYENC-62
CD ..\HWYENC-62
%PCLINK11% HWYENC.OBJ > HWYENC-my.log
RENAME HWYENC.SAV HWYENC-my.SAV
RENAME HWYENC.MAP HWYENC-my.MAP
RENAME HWYENC.STB HWYENC-my.STB
rem
echo LZSAV
CD ..\LZSAV
%PCLINK11% LZSAV.OBJ > LZSAV-my.log
RENAME LZSAV.SAV LZSAV-my.SAV
RENAME LZSAV.MAP LZSAV-my.MAP
RENAME LZSAV.STB LZSAV-my.STB
rem
echo MAIN-50
CD ..\MAIN-50
%PCLINK11% MAIN.OBJ LEVELS.OBJ > MAIN-my.log
RENAME MAIN.SAV MAIN-my.SAV
RENAME MAIN.MAP MAIN-my.MAP
RENAME MAIN.STB MAIN-my.STB
rem
echo RTLEM
CD ..\RTLEM
%PCLINK11% RTLEM.OBJ > RTLEM-my.log
RENAME RTLEM.SAV RTLEM-my.SAV
RENAME RTLEM.MAP RTLEM-my.MAP
RENAME RTLEM.STB RTLEM-my.STB
rem
echo SOKOBA
CD ..\SOKOBA
%PCLINK11% SOKOBA.OBJ SOKDAT.OBJ ALP.OBJ RALP.OBJ SOKMAZ.OBJ > SOKOBA-my.log
RENAME SOKOBA.SAV SOKOBA-my.SAV
RENAME SOKOBA.MAP SOKOBA-my.MAP
RENAME SOKOBA.STB SOKOBA-my.STB
rem
echo SOKOED
CD ..\SOKOED
%PCLINK11% SOKOED.OBJ SOKED.OBJ SOKDAT.OBJ > SOKOED-my.log
RENAME SOKOED.SAV SOKOED-my.SAV
RENAME SOKOED.MAP SOKOED-my.MAP
RENAME SOKOED.STB SOKOED-my.STB
rem
echo TSTPAL-01B
CD ..\TSPAL-01B
%PCLINK11% TSPAL.OBJ > TSPAL-my.log
RENAME TSPAL.SAV TSPAL-my.SAV
RENAME TSPAL.MAP TSPAL-my.MAP
RENAME TSPAL.STB TSPAL-my.STB
rem
echo TSTVM2-03A
CD ..\TSTVM2-03A
%PCLINK11% TSTVM2.OBJ > TSTVM2-my.log
RENAME TSTVM2.SAV TSTVM2-my.SAV
RENAME TSTVM2.MAP TSTVM2-my.MAP
RENAME TSTVM2.STB TSTVM2-my.STB
CD ..
