
START:

.GLOBL foo

K002:	.BYTE	foo
	.BYTE   0
	.WORD   foo

	MOV	#foo, R0
	MOVB	#foo, R0

K004:	MOV	foo, R0
	MOVB	foo, R0

	MOV	@foo, R0
	MOVB	@foo, R0

K005:	MOVB	#<foo + 1>, R0
	MOV	#<foo + 1>, R0

	MOVB	@#<foo + 1>, R0
	MOV	@#<foo + 1>, R0

	.BYTE	<foo + 1>
	.BYTE	0
	.WORD	<foo + 1>

K006:	MOVB	<foo + 1>, R0
	MOV	<foo + 1>, R0

K017:	.BYTE	<foo + foo>
	.BYTE	0
	.WORD	<foo + foo>

	.END START
